[package]
name = "net_wasabi"
version = "0.1.0"
edition = "2021"

[dependencies]
saba_core = { path = "../../saba_core" }
noli = { git = "http://github.com/hikalium/wasabi.git", branch = "for_saba" }
